trigger:
  - master

pool:
  vmImage: "windows-latest"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Compile Project"
    inputs:
      command: publish
      publishWebProjects: false
      projects: "**/RecieptManagerAPI/*.csproj"
      zipAfterPublish: true
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: 'Unit Tests'
    inputs:
      command: test
      projects: '**/*UnitTests/*UnitTests.csproj'

  
  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy to Stage Slot"
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Mi primera subscripcion de Azure(1)(238ca010-f875-4ebe-b5d0-1006ab33e7b9)'
      appType: 'webApp'
      WebAppName: 'recieptManager'
      packageForLinux: '$(System.DefaultWorkingDirectory)/RecieptManagerAPI/**/*.zip'
      AppSettings: '-ASPNETCORE_ENVIRONMENT Development'
  
  - task: DotNetCoreCLI@2
    displayName: 'E2E Tests'
    inputs:
      command: test
      projects: '**/*E2ETests/*E2ETests.csproj'